import Link from 'next/link'
import { ArrowUpRight, CheckCircle2, MapPin } from '@/components/icons'
import { jobs, services, technologies, tx } from '@/data/site'
import type { Locale } from '@/lib/i18n'
import { Reveal } from './Effects'
import { InteriorCTA, PageHero } from './PageShell'

const pc={
 uz:{about:['Biz fazoviy ma’lumotga ma’no beramiz.','GEOLDATA TECH — davlat va biznesning murakkab hududiy vazifalarini aniq raqamli tizimlarga aylantiradigan geoaxborot kompaniyasi.','Bizning yo‘nalishimiz','Markaziy Osiyodan global geospatial bozorga.','Missiya','Geografik ma’lumotlarni aqlli, ochiq va masshtablanuvchi raqamli tizimlarga aylantirish.','Vizyon','Davlatlar va tashkilotlar uchun Markaziy Osiyodagi yetakchi geospatial texnologik hamkor bo‘lish.','Tamoyillar'],services:['Fazoviy texnologiyaning to‘liq sikli.','Strategiya va ma’lumot auditidan enterprise platformani ishga tushirishgacha bo‘lgan barcha texnik qatlamlar.','Biznes muammosidan ishlaydigan tizimgacha.'],solutions:['Hudud uchun tayyor raqamli yechimlar.','Davlat, qishloq xo‘jaligi, shahar, ekologiya va infratuzilma uchun modulli geospatial mahsulotlar.','Natijaga yo‘naltirilgan modullar'],technologies:['Ishonchli tizimlar ishonchli stackdan boshlanadi.','GIS, data, frontend, backend va infratuzilmaning sinovdan o‘tgan texnologik ekotizimi.','Tizim arxitekturasi'],industries:['Har bir sohaning o‘z geografiyasi bor.','Biz sohaga xos jarayonlarni fazoviy ma’lumot bilan bog‘laymiz va boshqaruv uchun yagona manzara yaratamiz.','Sohalar bo‘yicha qiymat'],insights:['Fazoviy texnologiya haqida chuqur fikr.','GIS, ArcGIS, sun’iy yo‘ldosh monitoringi va raqamli transformatsiya bo‘yicha amaliy tahlillar.','So‘nggi materiallar'],careers:['Murakkab masalalarni yaxshi ko‘radiganlar uchun.','GIS, dizayn va dasturiy muhandislik kesishgan joyda ishlaydigan jamoaga qo‘shiling.','Ochiq pozitsiyalar']},
 ru:{about:['Мы придаем смысл пространственным данным.','GEOLDATA TECH превращает сложные территориальные задачи государства и бизнеса в точные цифровые системы.','Наше направление','Из Центральной Азии на глобальный георынок.','Миссия','Превращать геоданные в интеллектуальные, доступные и масштабируемые системы.','Видение','Стать ведущим геотехнологическим партнером в Центральной Азии.','Принципы'],services:['Полный цикл геотехнологий.','Все технические слои — от стратегии и аудита данных до запуска enterprise-платформы.','От бизнес-задачи к работающей системе.'],solutions:['Готовые цифровые решения для территорий.','Модульные геопродукты для государства, сельского хозяйства, города, экологии и инфраструктуры.','Модули, ориентированные на результат'],technologies:['Надежные системы начинаются с надежного стека.','Проверенная экосистема GIS, data, frontend, backend и инфраструктуры.','Архитектура системы'],industries:['У каждой отрасли своя география.','Мы связываем отраслевые процессы с геоданными и создаем единую картину управления.','Ценность для отраслей'],insights:['Глубокий взгляд на геотехнологии.','Практические материалы о GIS, ArcGIS, спутниковом мониторинге и цифровой трансформации.','Последние материалы'],careers:['Для тех, кто любит сложные задачи.','Присоединяйтесь к команде на пересечении GIS, дизайна и программной инженерии.','Открытые позиции']},
 en:{about:['We give spatial data meaning.','GEOLDATA TECH turns complex territorial challenges for governments and businesses into precise digital systems.','Our direction','From Central Asia to the global geospatial market.','Mission','Transform geographic data into intelligent, accessible, and scalable digital systems.','Vision','Become a leading geospatial technology partner across Central Asia.','Principles'],services:['The full geospatial technology cycle.','Every technical layer, from strategy and data audit to an enterprise platform launch.','From business challenge to working system.'],solutions:['Digital solutions built for territories.','Modular geospatial products for government, agriculture, cities, environment, and infrastructure.','Outcome-driven modules'],technologies:['Reliable systems start with a reliable stack.','A proven ecosystem across GIS, data, frontend, backend, and infrastructure.','System architecture'],industries:['Every industry has its own geography.','We connect sector workflows with spatial data to create one operational picture.','Industry value'],insights:['Deep thinking about geospatial technology.','Practical perspectives on GIS, ArcGIS, satellite monitoring, and digital transformation.','Latest intelligence'],careers:['For people who enjoy hard problems.','Join a team working where GIS, design, and software engineering meet.','Open positions']}
}
const values={
 uz:['Aniqlik','Innovatsiya','Ishonchlilik','Shaffoflik','Hamkorlik','Ta’sir','Xavfsizlik','Masshtablanish'],
 ru:['Точность','Инновации','Надёжность','Прозрачность','Партнёрство','Влияние','Безопасность','Масштабируемость'],
 en:['Precision','Innovation','Reliability','Transparency','Partnership','Impact','Security','Scalability']
}
const timeline={
 uz:[['2014','ASOS SOLISH','Yangi geoaxborot yo‘nalishi boshlandi.'],['2017','KORPORATIV GIS','Korporativ GIS tizimlari va barqaror platformalar.'],['2020','YO‘LDOSH ANALITIKA','Sun’iy yo‘ldosh tahlili va monitoring yechimlari.'],['2023','MARKAZIY OSIYO','Hududiy miqyosdagi tizimlar va mintaqaviy qamrov.'],['2026','FAZOVIY AI','Fazoviy intellektning yangi qatlami.']],
 ru:[['2014','ОСНОВАНИЕ','Начало нового геоинформационного направления.'],['2017','КОРПОРАТИВНЫЙ GIS','Корпоративные GIS-системы и устойчивые платформы.'],['2020','СПУТНИКОВАЯ АНАЛИТИКА','Спутниковый анализ и решения мониторинга.'],['2023','ЦЕНТРАЛЬНАЯ АЗИЯ','Системы регионального масштаба и охват.'],['2026','ПРОСТРАНСТВЕННЫЙ AI','Новый слой географического интеллекта.']],
 en:[['2014','FOUNDATION','A new layer of geographic intelligence began.'],['2017','ENTERPRISE GIS','Enterprise GIS systems and resilient platforms.'],['2020','SATELLITE ANALYTICS','Satellite analysis and monitoring solutions.'],['2023','CENTRAL ASIA','Regional-scale systems and resilient platforms.'],['2026','SPATIAL AI','A new layer of geographic intelligence.']]
}
export function AboutPage({locale}:{locale:Locale}){const c=pc[locale].about;const v=values[locale];const tl=timeline[locale];return <><PageHero locale={locale} index="01" eyebrow={locale==='uz'?'KOMPANIYA':locale==='ru'?'О КОМПАНИИ':'ABOUT'} title={c[0]} text={c[1]}/><section className="editorial-section"><Reveal><span className="section-label">/ {c[2]}</span><h2>{c[3]}</h2></Reveal><div className="mission-grid"><article><span>01</span><h3>{c[4]}</h3><p>{c[5]}</p></article><article><span>02</span><h3>{c[6]}</h3><p>{c[7]}</p></article></div></section><section className="timeline-section"><span className="section-label">/ {locale==='uz'?'XRONOLOGIYA':locale==='ru'?'ХРОНОЛОГИЯ':'TIMELINE'}</span><div className="timeline">{tl.map(row=><Reveal key={row[0]}><div><small>{row[0]}</small><i/><h3>{row[1]}</h3><p>{row[2]}</p></div></Reveal>)}</div></section><section className="values-section"><Reveal><span className="section-label">/ {c[8]}</span><h2>{locale==='uz'?<>Aniqlik atrofida qurilgan.<br/>Ta’sir uchun yaratilgan.</>:locale==='ru'?<>Построены вокруг точности.<br/>Созданы ради влияния.</>:<>Built around precision.<br/>Designed for impact.</>}</h2></Reveal><div>{v.map((item,i)=><article key={item}><small>0{i+1}</small><h3>{item}</h3><span/></article>)}</div></section><section className="coverage-section"><div className="coverage-map"><div className="topo"/>{[1,2,3,4,5].map(i=><i key={i} className={'coverage-dot d'+i}/>)}</div><Reveal><span className="section-label">/ {locale==='uz'?'GEOGRAFIK QAMROV':locale==='ru'?'ГЕОГРАФИЧЕСКИЙ ОХВАТ':'GEOGRAPHIC COVERAGE'}</span><h2>{locale==='uz'?'Markaziy Osiyo yagona ma’lumot tili bilan bog‘langan.':locale==='ru'?'Центральная Азия связана единым языком данных.':'Central Asia connected by one data language.'}</h2><p>{c[1]}</p></Reveal></section><InteriorCTA locale={locale} title={locale==='uz'?'Hududingiz uchun yangi raqamli qatlam yarataylik.':locale==='ru'?'Создадим новый цифровой слой для вашей территории.':'Let’s create a new digital layer for your territory.'}/></>}
export function ServicesPage({locale}:{locale:Locale}){const c=pc[locale].services;return <><PageHero locale={locale} index="02" eyebrow={locale==='uz'?'XIZMATLAR':locale==='ru'?'УСЛУГИ':'SERVICES'} title={c[0]} text={c[1]}/><section className="service-detail-list"><div className="section-head"><Reveal><span className="section-label">/ {locale==='uz'?'IMKONIYATLAR':locale==='ru'?'ВОЗМОЖНОСТИ':'CAPABILITIES'}</span><h2>{c[2]}</h2></Reveal></div>{services.map((s,i)=><article id={s.slug} key={s.slug}><div className="detail-index">0{i+1}</div><div><small>{tx(s.capabilities[0],locale)}</small><h2>{tx(s.title,locale)}</h2><p>{tx(s.summary,locale)}</p></div><ul>{s.capabilities.map(x=><li key={x.en}><CheckCircle2/>{tx(x,locale)}</li>)}</ul></article>)}</section><InteriorCTA locale={locale} title={locale==='en'?'One partner for every spatial layer.':locale==='ru'?'Один партнер для каждого пространственного слоя.':'Har bir fazoviy qatlam uchun yagona hamkor.'}/></>}
export function TechnologiesPage({locale}:{locale:Locale}){const c=pc[locale].technologies;const arch=locale==='uz'?<>Ma’lumot oqadi. Tizimlar javob beradi.<br/>Qarorlar tezlashadi.</>:locale==='ru'?<>Данные текут. Системы отвечают.<br/>Решения ускоряются.</>:<>Data flows. Systems respond.<br/>Decisions accelerate.</>;return <><PageHero locale={locale} index="06" eyebrow={locale==='uz'?'TEXNOLOGIYALAR':locale==='ru'?'ТЕХНОЛОГИИ':'TECHNOLOGIES'} title={c[0]} text={c[1]}/><section className="architecture-section"><Reveal><span className="section-label">/ {c[2]}</span><h2>{arch}</h2></Reveal><div className="architecture-diagram"><div className="arch-core">GEODATA<br/>PLATFORM</div>{Object.keys(technologies).map((x,i)=><div key={x} className={'arch-node n'+i}><span>{x}</span><i/></div>)}<svg><path d="M110 250 C250 20 550 20 690 250"/><path d="M110 250 C250 480 550 480 690 250"/><path d="M400 40V460"/></svg></div></section><section className="tech-catalog">{Object.entries(technologies).map(([group,items],i)=><article key={group}><small>0{i+1}</small><h2>{group}</h2><div>{items.map(x=><span key={x}>{x}</span>)}</div></article>)}</section><InteriorCTA locale={locale} title={locale==='en'?'Architecture that scales with your geography.':locale==='ru'?'Архитектура, которая масштабируется вместе с вашей географией.':'Geografiyangiz bilan birga masshtablanadigan arxitektura.'}/></>}
export function CareersPage({locale}:{locale:Locale}){const c=pc[locale].careers;const benefits=locale==='uz'?['Chuqur texnik ish','Haqiqiy ta’sir','O‘qish byudjeti','Gibrid madaniyat','Xalqaro qamrov','Yuqori muhandislik standartlari']:locale==='ru'?['Глубокая техническая работа','Реальное влияние','Бюджет на обучение','Гибридная культура','Международный охват','Высокие инженерные стандарты']:['Deep technical work','Real-world impact','Learning budget','Hybrid culture','International scope','Strong engineering standards'];const positionsLabel=locale==='uz'?`${jobs.length} ta pozitsiya / Toshkent + masofaviy`:locale==='ru'?`${jobs.length} позиций / Ташкент + удалённо`:`${jobs.length} positions / Tashkent + Remote`;return <><PageHero locale={locale} index="09" eyebrow={locale==='uz'?'KARYERA':locale==='ru'?'КАРЬЕРА':'CAREERS'} title={c[0]} text={c[1]}/><section className="culture-section"><div className="culture-visual"><div className="topo"/><strong>GIS × CODE × DESIGN</strong></div><Reveal><span className="section-label">/ {locale==='uz'?'MADANIYAT':locale==='ru'?'КУЛЬТУРА':'CULTURE'}</span><h2>{locale==='uz'?'Hududlar ishlashini o‘zgartiradigan tizimlar yarating.':locale==='ru'?'Создавайте системы, которые меняют работу территорий.':'Build systems that change how territories work.'}</h2><p>{c[1]}</p><div className="benefit-list">{benefits.map(x=><span key={x}><CheckCircle2/>{x}</span>)}</div></Reveal></section><section className="jobs-section"><Reveal><span className="section-label">/ {c[2]}</span><h2>{positionsLabel}</h2></Reveal><div>{jobs.map((j,i)=><article key={j.title.en}><small>0{i+1}</small><h3>{tx(j.title,locale)}</h3><span>{tx(j.type,locale)}</span><span><MapPin/>{tx(j.location,locale)}</span><Link href={`/${locale}/careers/apply?position=${encodeURIComponent(j.title.en)}`}><ArrowUpRight/></Link></article>)}</div></section><InteriorCTA locale={locale} title={locale==='en'?'Your next coordinate may be here.':locale==='ru'?'Возможно, ваша следующая координата здесь.':'Keyingi koordinatangiz shu yerda bo‘lishi mumkin.'}/></>}

