'use client'
import dynamic from 'next/dynamic'
import Link from 'next/link'
import Image from 'next/image'
import { ArrowDown, ArrowRight, ArrowUpRight, Cpu, Layers3, Orbit, Radar, Satellite, Sparkles } from 'lucide-react'
import { motion, useScroll, useTransform } from 'framer-motion'
import { useRef } from 'react'
import { projects, services, technologies, testimonials, tx, ui } from '@/data/site'
import type { Locale } from '@/lib/i18n'
import { Reveal, Magnetic } from './Effects'
import { ProjectMap } from './ProjectMap'
const Globe=dynamic(()=>import('./Globe'),{ssr:false,loading:()=> <div className="globe-placeholder"><span/></div>})

const homeCopy={
 uz:{eyebrow:'Fazoviy intellekt · Markaziy Osiyo',title:<>Geografik ma’lumotni<br/><em>raqamli intellektga</em><br/>aylantiramiz.</>,desc:'GEOLDATA TECH davlatlar va biznes uchun ilg‘or GIS tizimlari, ArcGIS portallari, interaktiv xaritalar va korporativ veb-platformalarni yaratadi.',trusted:'Ishonchli texnologik hamkor',intro:'Geografiya endi shunchaki xarita emas.',intro2:'U — qaror qabul qilish tizimi.',introText:'Biz sun’iy yo‘ldoshdan tortib dala sensori va idoraviy bazalargacha bo‘lgan ma’lumotlarni yagona, tushunarli va boshqariladigan fazoviy platformaga birlashtiramiz.',serviceLabel:'Imkoniyatlar',serviceTitle:'Murakkab fazoviy vazifalar uchun chuqur texnologiya.',mapLabel:'Loyihalar xaritasi',mapTitle:'Haqiqiy hududlar. O‘lchanadigan natijalar.',projectLabel:'Tanlangan loyihalar',projectTitle:'Tizimlarimiz xaritadan tashqarida ham ishlaydi.',techLabel:'Texnologik ekotizim',techTitle:'Har bir qatlam uchun ishonchli texnologik stack.',industryLabel:'Sohalar',industryTitle:'Bir platforma. Turli vazifalar.',statLabel:'Masshtab',statTitle:'Raqamlar ortida ishlaydigan tizimlar.',processLabel:'Ishlash jarayoni',processTitle:'G‘oyadan barqaror platformagacha.',testimonialLabel:'Hamkorlar fikri',insightLabel:'Tahlillar',insightTitle:'Geoaxborot kelajagi haqida.',cta:'Keyingi avlod geoaxborot tizimini birga quramiz.',scroll:'PASTGA',geoLabel:'GEOGRAFIK INTELLEKT',selectPoint:'GEO NUQTANI TANLANG',nextDest:'KEYINGI MANZIL',stats:[['30+','GIS LOYIHALAR'],['15+','RAQAMLI PLATFORMA'],['10+','QAMRAB OLINGAN HUDUD'],['1M+','FAZOVIY YOZUV'],['99.9%','ISHONCHLILIK']],floatLabels:['YO‘LDOSH MONITORING','ARCGIS INTEGRATSIYA','REAL VAQT MA’LUMOT'],partners:['Davlat tashkilotlari','Agrokompaniyalar','Infratuzilma operatorlari','Ekologik tashkilotlar','Hududiy hokimliklar','Korporativ mijozlar']},
 ru:{eyebrow:'Пространственный интеллект · Центральная Азия',title:<>Превращаем геоданные<br/>в <em>цифровой интеллект.</em></>,desc:'GEOLDATA TECH создает передовые GIS-системы, порталы ArcGIS, интерактивные карты и корпоративные веб-платформы для государства и бизнеса.',trusted:'Надёжный технологический партнер',intro:'География — больше не просто карта.',intro2:'Это система принятия решений.',introText:'Мы объединяем спутниковые, полевые и ведомственные данные в единую, понятную и управляемую пространственную платформу.',serviceLabel:'Возможности',serviceTitle:'Глубокие технологии для сложных пространственных задач.',mapLabel:'Карта проектов',mapTitle:'Реальные территории. Измеримые результаты.',projectLabel:'Избранные проекты',projectTitle:'Наши системы работают далеко за пределами карты.',techLabel:'Технологическая экосистема',techTitle:'Надёжный стек для каждого слоя.',industryLabel:'Отрасли',industryTitle:'Одна платформа. Разные задачи.',statLabel:'Масштаб',statTitle:'Системы, стоящие за этими цифрами.',processLabel:'Этапы работы',processTitle:'От идеи до устойчивой платформы.',testimonialLabel:'Отзывы партнеров',insightLabel:'Аналитика',insightTitle:'О будущем геотехнологий.',cta:'Создадим вместе новое поколение геосистем.',scroll:'ДАЛЕЕ',geoLabel:'ГЕОГРАФИЧЕСКИЙ ИНТЕЛЛЕКТ',selectPoint:'ВЫБЕРИТЕ ГЕОТОЧКУ',nextDest:'СЛЕДУЮЩЕЕ НАПРАВЛЕНИЕ',stats:[['30+','GIS-ПРОЕКТЫ'],['15+','ЦИФРОВЫЕ ПЛАТФОРМЫ'],['10+','ОХВАЧЕННЫЕ РЕГИОНЫ'],['1M+','ПРОСТРАНСТВЕННЫЕ ЗАПИСИ'],['99.9%','НАДЁЖНОСТЬ']],floatLabels:['СПУТНИКОВЫЙ МОНИТОРИНГ','ИНТЕГРАЦИЯ ARCGIS','ДАННЫЕ В РЕАЛЬНОМ ВРЕМЕНИ'],partners:['Государственные организации','Агрокомпании','Инфраструктурные операторы','Экологические организации','Региональные власти','Корпоративные клиенты']},
 en:{eyebrow:'Spatial intelligence · Central Asia',title:<>Turning geographic data<br/>into <em>digital intelligence.</em></>,desc:'GEOLDATA TECH designs advanced GIS systems, ArcGIS portals, interactive maps, and enterprise web platforms for governments and forward-thinking businesses.',trusted:'Trusted technology partner',intro:'Geography is no longer just a map.',intro2:'It is a decision-making system.',introText:'We unite satellite, field, and institutional data into one clear, governable spatial platform built for action.',serviceLabel:'Capabilities',serviceTitle:'Deep technology for complex spatial challenges.',mapLabel:'Project map',mapTitle:'Real territories. Measurable outcomes.',projectLabel:'Featured projects',projectTitle:'Our systems work far beyond the map.',techLabel:'Technology ecosystem',techTitle:'A reliable stack for every layer.',industryLabel:'Industries',industryTitle:'One platform. Different missions.',statLabel:'Scale',statTitle:'Operational systems behind the numbers.',processLabel:'Delivery route',processTitle:'From idea to resilient platform.',testimonialLabel:'Partner perspectives',insightLabel:'Insights',insightTitle:'Thinking about what comes next.',cta:'Let’s build the next generation of geospatial systems.',scroll:'SCROLL',geoLabel:'GEOGRAPHIC INTELLIGENCE',selectPoint:'SELECT A GEO POINT',nextDest:'NEXT DESTINATION',stats:[['30+','GIS PROJECTS'],['15+','DIGITAL PLATFORMS'],['10+','REGIONS COVERED'],['1M+','SPATIAL RECORDS'],['99.9%','RELIABILITY']],floatLabels:['SATELLITE MONITORING','ARCGIS INTEGRATION','REAL-TIME DATA'],partners:['Government organizations','Agriculture companies','Infrastructure operators','Environmental organizations','Regional authorities','Enterprise clients']}
}
const process={
 uz:['Kashfiyot','Fazoviy ma’lumot auditi','Tizim arxitekturasi','UX va xarita dizayni','Ishlab chiqish','GIS integratsiyasi','Sinov','Ishga tushirish','Qo‘llab-quvvatlash'],
 ru:['Исследование','Аудит геоданных','Архитектура','UX и дизайн карт','Разработка','GIS-интеграция','Тестирование','Запуск','Поддержка и рост'],
 en:['Discovery','Spatial data audit','System architecture','UX & map design','Development','GIS integration','Testing','Deployment','Support & scale']
}
export function Home({locale}:{locale:Locale}){
 const c=homeCopy[locale],t=ui[locale];const hero=useRef(null);const {scrollYProgress}=useScroll({target:hero,offset:['start start','end start']});const globeY=useTransform(scrollYProgress,[0,1],[0,180]);const textY=useTransform(scrollYProgress,[0,1],[0,90])
 return <>
 <section className="home-hero" ref={hero}><Image src="/images/geospatial-terrain.png" alt="" fill priority sizes="100vw" className="hero-terrain"/><div className="hero-overlay"/><div className="hero-grid"/>
  <motion.div className="hero-globe" style={{y:globeY}}><Globe/></motion.div>
  <motion.div className="hero-copy-block" style={{y:textY}}><div className="kicker"><span/><Radar/> {c.eyebrow}</div><h1>{c.title}</h1><p>{c.desc}</p><div className="hero-buttons"><Magnetic><Link className="button-primary" href={`/${locale}/services`}>{t.explore}<ArrowUpRight/></Link></Magnetic><Link className="button-ghost" href={`/${locale}/contact`}>{t.start}<ArrowRight/></Link></div></motion.div>
  <div className="floating-label label-a"><Satellite/> {c.floatLabels[0]}</div><div className="floating-label label-b"><Orbit/> {c.floatLabels[1]}</div><div className="floating-label label-c"><Layers3/> {c.floatLabels[2]}</div>
  <a href="#intro" className="scroll-down"><span>{c.scroll}</span><ArrowDown/></a>
 </section>
 <section className="trust-strip"><span>{c.trusted}</span>{c.partners.map((p,i)=><div key={p}><i>0{i+1}</i>{p}</div>)}</section>
 <section className="intro-section" id="intro"><div className="section-coordinate">41.2995° N<br/>69.2401° E</div><Reveal><span className="section-label">/ 01 — {c.geoLabel}</span><h2>{c.intro}<br/><em>{c.intro2}</em></h2></Reveal><Reveal className="intro-aside"><p>{c.introText}</p><Link href={`/${locale}/about`}>{t.view}<ArrowUpRight/></Link><div className="mini-orbit"><i/><i/></div></Reveal></section>
 <section className="services-story"><div className="section-head"><Reveal><span className="section-label">/ 02 — {c.serviceLabel}</span><h2>{c.serviceTitle}</h2></Reveal><p>GIS / ARCGIS / WEBGL / REMOTE SENSING</p></div><div className="service-lines">{services.map((s,i)=><Reveal key={s.slug}><Link href={`/${locale}/services#${s.slug}`} className="service-line"><small>0{i+1}</small><h3>{tx(s.title,locale)}</h3><p>{tx(s.summary,locale)}</p><div className="service-visual"><span/><span/><span/></div><ArrowUpRight/></Link></Reveal>)}</div></section>
 <section className="map-section"><div className="section-head light"><Reveal><span className="section-label">/ 03 — {c.mapLabel}</span><h2>{c.mapTitle}</h2></Reveal><p>{c.selectPoint}</p></div><ProjectMap locale={locale}/></section>
 <section className="featured-section"><div className="section-head"><Reveal><span className="section-label">/ 04 — {c.projectLabel}</span><h2>{c.projectTitle}</h2></Reveal><Link href={`/${locale}/projects`}>{t.all}<ArrowUpRight/></Link></div><div className="project-rail">{projects.map((p,i)=><Link key={p.slug} href={`/${locale}/projects/${p.slug}`} className="project-slide" style={{'--project-color':p.color} as React.CSSProperties}><div className="project-visual"><Image src={p.image} alt={tx(p.title,locale)} fill sizes="320px" className="project-visual-img"/><span className="project-number">0{i+1}</span></div><div><small>{p.category} · {p.year}</small><h3>{tx(p.title,locale)}</h3><p>{tx(p.location,locale)} — {tx(p.result,locale)}</p></div><ArrowUpRight/></Link>)}</div></section>
 <section className="tech-section"><div className="tech-network"><div className="network-core"><Cpu/><span>GEODATA<br/>CORE</span></div>{Object.keys(technologies).map((k,i)=><span key={k} className={'network-node node-'+i}>{k}</span>)}<svg><circle cx="50%" cy="50%" r="31%"/><circle cx="50%" cy="50%" r="44%"/></svg></div><Reveal className="tech-copy"><span className="section-label">/ 05 — {c.techLabel}</span><h2>{c.techTitle}</h2><div className="tech-groups">{Object.entries(technologies).map(([group,items])=><div key={group}><b>{group}</b><p>{items.slice(0,6).join(' · ')}</p></div>)}</div><Link href={`/${locale}/technologies`}>{t.view}<ArrowUpRight/></Link></Reveal></section>
 <section className="stats-section"><Reveal><span className="section-label">/ 06 — {c.statLabel}</span><h2>{c.statTitle}</h2></Reveal><div className="stat-grid">{c.stats.map((s,i)=><Reveal delay={i*.07} key={s[1]}><div className="stat-cell"><strong>{s[0]}</strong><span>{s[1]}</span></div></Reveal>)}</div></section>
 <section className="process-section"><Reveal><span className="section-label">/ 07 — {c.processLabel}</span><h2>{c.processTitle}</h2></Reveal><div className="route-line"><i/></div><div className="process-grid">{process[locale].map((v,i)=><div key={v}><small>{String(i+1).padStart(2,'0')}</small><span/><h3>{v}</h3></div>)}</div></section>
 <section className="testimonials"><span className="section-label">/ 08 — {c.testimonialLabel}</span>{testimonials.map((item,i)=><Reveal key={item.name}><blockquote><Sparkles/><p>“{tx(item.quote,locale)}”</p><footer><strong>{item.name}</strong><span>{tx(item.role,locale)} · {tx(item.org,locale)}</span></footer><small>0{i+1}</small></blockquote></Reveal>)}</section>
 <section className="final-cta"><div className="cta-grid"/><div className="cta-horizon"/><Reveal><span>41.2995° N / {c.nextDest}</span><h2>{c.cta}</h2><Magnetic><Link href={`/${locale}/contact`}>{t.start}<ArrowUpRight/></Link></Magnetic></Reveal></section>
 </>}

